name: Codeleft Coverage Assessment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeleft-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out your code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install codeleft-cli from source
        run: |
          go install github.com/henrylamb/codeleft-cli/cmd/codeleft-cli@latest

      - name: Verify codeleft-cli installation
        run: |
          codeleft-cli --version || true
          which codeleft-cli

      - name: Run codeleft-cli coverage
        run: |
          # Execute the CLI against the code in this repo (checked out above)
          codeleft-cli --asses-coverage \
                       --threshold-percent=80 \
                       --threshold-grade=A \
                       --tools "SOLID, OWASP-TOP-10"
