name: Codeleft CLI Usage

on: [push, pull_request]

jobs:
  run-codeleft-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Download codeleft-cli binary
        run: |
          # Adjust the URL to your actual release asset
          wget https://github.com/your-org/codeleft-cli/releases/download/v1.0.0/codeleft-cli_1.0.0_Linux_x86_64.tar.gz \
               -O codeleft-cli.tar.gz

      - name: Install codeleft-cli
        run: |
          tar -xzf codeleft-cli.tar.gz
          chmod +x codeleft-cli-linux-amd64
          sudo mv codeleft-cli-linux-amd64 /usr/local/bin/codeleft-cli

      - name: Run codeleft-cli
        run: |
          codeleft-cli --asses-coverage \
                       --threshold-percent=80 \
                       --threshold-grade=A \
                       --tools "SOLID, OWASP-TOP-10"
