name: Codeleft Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-codeleft-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo to analyze
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install codeleft-cli
        run: |
          # If the main package is in cmd/codeleft-cli
          go install github.com/henrylamb/codeleft-cli/cmd/codeleft-cli@latest

      - name: Verify codeleft-cli
        run: |
          which codeleft-cli
          codeleft-cli --version

      - name: Run codeleft-cli coverage
        run: |
          codeleft-cli --asses-coverage \
                       --threshold-percent=80 \
                       --threshold-grade=A \
                       --tools "SOLID, OWASP-TOP-10"
